////////////////////////////////////////////////////
// Low-level literal syntax
digit      : /[0-9]/
digits     : /[0-9]+/
hex_digit  : /[0-9a-fA-F]/
hex_digits : /[0-9a-fA-F]+/
letter     : /[a-zA-Z]/
letters    : /[a-zA-Z]+/
underscore : /[_]/
true       : "true"
false      : "false"

// Literals
bool_literal : true | false
decimal_literal : digits
hexadecimal_literal : "0x" hex_digits
?integer_literal : decimal_literal | hexadecimal_literal
negated_integer_literal : "-" integer_literal
?posneg_integer_literal : integer_literal | negated_integer_literal
float_literal : /[-+]?[0-9]+[.][0-9]*([eE][-+]?[0-9]+)?/
string_literal  : ESCAPED_STRING
?constant_literal : bool_literal | posneg_integer_literal | float_literal | string_literal
unknown_dim_literal : "?"

// Identifier syntax (loosely following MLIR conventions)
bare_id : (letter| underscore) (letter|digit|underscore)*
suffix_id : digits | bare_id
identifier : "%" suffix_id

// Scalar types
!float_type : "f16" | "f32"
!int_type : "i8" | "i16" | "i32" | "i64"
!uint_type : "u8" | "u16" | "u32" | "u64"
!bool_type : "bool"
?standard_type : float_type | int_type | uint_type | bool_type

// Built-in enumerations
!schedule_type : "PARALLEL" | "FORWARD" | "BACKWARD"
enum_literal : schedule_type

// Language built-in types
?dim : integer_literal | unknown_dim_literal
dim_list: dim ("," dim)*
extent_tuple : "(" dim ("," dim)* ")"
extent_tuple_list : extent_tuple ("," extent_tuple)*
extent_type : "extent" "<" extent_tuple_list ">"
domain_type : "domain" "<" dim_list ">"
field_type : "field" "<" domain_type "," extent_type "," standard_type ">"
interval_type : "interval" "<" (dim | "None") "," (dim | "None") ">"
multi_interval_type : "[" interval_type ("," interval_type)* "]"
?builtin_type : field_type | domain_type | extent_type | interval_type | multi_interval_type

////////////////////////////////////////////////////
// Common syntactic elements
id_list : identifier ("," identifier)*
params : "(" id_list? ")"
type_list : field_type ("," field_type)*

attr : bare_id "=" (identifier | constant_literal | enum_literal | builtin_type)
attributes : "{" attr? ("," attr)* "}"

// Define program
program : id_list "=" "stencil.program" params attributes ":" type_list "->" type_list program_body

// Define computation
computation : id_list "=" "stencil.computation" params attributes ":" type_list "->" type_list computation_body

// Define stencil statement
statement : id_list "=" "stencil.statement" params attributes ":" type_list "->" type_list statement_body

////////////////////////////////////////////////////
// Define contents of stencil statements
?parens : "(" value_expr ")"
unary_op : "-" value_expr
binary_op : value_expr ("+" | "-" | "*" | "/" | "%" | "<" | "<=" | ">" | ">=" | "==" | "!=") value_expr
ternary_op : value_expr "if" value_expr "else" value_expr
subscript_slice : posneg_integer_literal ("," posneg_integer_literal)*
subscript : identifier "[" subscript_slice "]"
function_call : bare_id "(" (value_expr ("," value_expr)*)? ")"

value_expr : constant_literal | identifier | parens | unary_op | binary_op | ternary_op | subscript | function_call
assign_expr : id_list "=" value_expr (";")?
return_expr : "return" value_expr (";")?
?statement_contents : assign_expr | return_expr

// TODO: Where should "stencil.if" reside?

////////////////////////////////////////////////////
// AST tree structure
program_body : "{" computation* "}"
computation_body : "{" statement* "}"
statement_body : "{" statement_contents* "}"

?start: program

////////////////////////////////////////////////////
// Lark imports
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%import common.NEWLINE

// Things to ignore: whitespace, single-line comments, multi-line comments
COMMENT : "//" /(.)+/ NEWLINE
MULTILINE_COMMENT: /\/\*(\*(?!\/)|[^*])*\*\//
%ignore WS
%ignore COMMENT
%ignore MULTILINE_COMMENT
